
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- logo -->
      <a class="navbar-brand" href="#"><img alt="" src="<?php print($this->url->get("img/imannova-logo.png"))?>"/></a>     
    </div>
    <div class="collapse navbar-collapse animated fadeIn" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav animated fadeIn text16">
        
        <li class="<?php print($menuSel == "configurar"? 'active':'');?>"><a href="<?php print($this->url->get('grupos')) ?>"><i class="gi gi-cogwheel"></i>   Grupos de Evaluación</a></li>
        <li class="<?php print($menuSel == "evaluar"? 'active':'');?>"><a href="<?php print($this->url->get('evaluacion')) ?>"><i class="gi gi-circle_ok"></i> Realizar Evaluación</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-download-alt"></span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<?php print($menuSel == "perfil"? 'active':'');?>"><a href="<?php print($this->url->get('perfil')) ?>"><i class="gi gi-user"></i>  Mi Perfil</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="gi gi-user"></i><b> Login</b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu">
                <li>
                     <div class="row">
                            <div class="col-md-12">
                                <!-- Login -->
                                <div class="social-buttons">
                                    <div class="iconSpecial"><i class="gi gi-unlock"></i> Login</div>
                                </div>                               
                                 <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
                                        <div class="form-group">
                                             <label class="sr-only" for="exampleInputEmail2">Correo</label>
                                             <input type="email" class="form-control" id="exampleInputEmail2" placeholder="usuario" required>
                                        </div>
                                        <div class="form-group">
                                             <label class="sr-only" for="exampleInputPassword2">Contraseña</label>
                                             <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Contraseña" required>
                                        </div>
                                        <div class="form-group">
                                             <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                                        </div>
                                 </form>
                            </div>                      
                     </div>
                </li>
            </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>