
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- logo -->
      <a class="navbar-brand" href="#"><img alt="" src="<?php print($this->url->get("img/imannova-logo.png"))?>"/></a>     
    </div>
    <div class="collapse navbar-collapse animated fadeIn" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav animated fadeIn text16">
        
        <li class="<?php print($menuSel == "configurar"? 'active':'');?>"><a href="<?php print($this->url->get('grupos')) ?>"><i class="gi gi-cogwheel"></i>   Grupos de Evaluación</a></li>
        <li class="<?php print($menuSel == "evaluar"? 'active':'');?>"><a href="<?php print($this->url->get('evaluacion')) ?>"><i class="gi gi-circle_ok"></i> Realizar Evaluación</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-download-alt"></span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<?php print($menuSel == "perfil"? 'active':'');?>"><a href="<?php print($this->url->get('perfil')) ?>"><i class="gi gi-user"></i>  Mi Perfil</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="gi gi-user"></i><b> <?php print(utf8_encode($this->auth->getIdentity()['name']))?></b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu">
                <li>
                     <div class="row">
                            <div class="col-md-12">1
                                      <div class="form-group">
                                          <a href="<?php print($this->url->get('')) ?>" class="btn btn-imannova btn-block"><i class="hi hi-cog"></i> Editar Datos</a>
                                      </div>
                                      <div class="form-group">
                                           <a href="<?php print($this->url->get('logout')) ?>" class="btn btn-imannova btn-block"><i class="gi gi-log_out"></i> Salir</a>
                                      </div>
                                 </form>
                            </div>                      
                     </div>
                </li>
            </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>