<!-- Widgets Row -->
<div class="row" style="padding-top: 40px;">
	<div class="col-lg-12 bhoechie-tab-container">
		<div class="col-lg-3 col-md-3 col-sm-5 bhoechie-tab-menu">
			<div class="list-group bg-color-primary  ">
				<a href="<?php echo $this->url->get("ajax/cargarCrearGrupo") ?>" 
				   data-action="<?php echo $this->url->get("ajax/cargarCrearGrupo") ?>"
				   data-eval=""
				   class="menu-config-grupo list-group-item bg-primary text-center ">
				<i class="fa fa-plus fa-3x "></i><br/>Nuevo Grupo de Evaluación
				</a>
				<div class="list-group-item inactive" style="height:200px;">
				</div>
			</div>
		</div>
		            
		<div class="col-lg-9 col-md-9 col-sm-7 bhoechie-tab">
		    <!-- flight section -->
		    <div class="bhoechie-tab-content fade in active">
		        <center>
		            <div id="listaGrupos">
		            	<?php print($this->view->render('evaluacion/configurar-grupos-lista',$pcData));?>
		            </div>

		        </center>
		    </div>
		</div>
	</div>
</div>


        <!-- Large Modal -->
        <div id="modal-nuevo-grupo" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
        </div>

        <!-- END Large Modal -->