<!-- Widgets Row -->
<div class="row" style="padding-top: 40px;">
	<div class="col-lg-12 bhoechie-tab-container">
		<div class="col-lg-3 col-md-3 col-sm-5 bhoechie-tab-menu">
			<div class="list-group bg-color-primary  ">
				<a href="#modal-nuevo-grupo" data-toggle="modal" class="menu-config-grupo list-group-item bg-primary text-center ">
				<i class="fa fa-plus fa-3x "></i><br/>Nuevo Grupo de Evaluación
				</a>
				<div class="list-group-item inactive" style="height:200px;">
				</div>
			</div>
		</div>
		            
		<div class="col-lg-9 col-md-9 col-sm-7 bhoechie-tab">
		    <!-- flight section -->
		    <div class="bhoechie-tab-content fade in active">
		        <center>
		            
		            <div class="block">
						<div class="block-title">
						<h2><strong>Grupos de </strong> Evaluación</h2>
						</div>
						<div class="table-responsive">
							<table class="table table-vcenter table-striped">
							<thead>
							<tr>
							<th>Nombre Grupo</th>
							<th>Nº Integrantes</th>
							<th>Nº Encuestas </th>
							<th style="width: 150px;" class="text-center">Acciones</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td><a href="<?php print($this->url->get('grupos/configurar')) ?>">Grupo de Soporte</a></td>
									<td><a href="javascript:void(0)" class="label label-default">10</a></td>
									<td><a href="javascript:void(0)" class="label label-default">5</a></td>
									<td class="text-center">
									<div class="btn-group btn-group-xs">
									<a href="<?php print($this->url->get('grupos/configurar')) ?>" data-toggle="tooltip" title="" class="btn btn-block btn-imannova" data-original-title="Configurar Grupo"><i class="gi gi-cogwheel"></i> Configurar grupo</a>
									</div>
									</td>
								</tr>
								<tr>
									<td><a href="<?php print($this->url->get('grupos/configurar')) ?>">Grupo de Gerencia</a></td>
									<td><a href="javascript:void(0)" class="label label-default">4</a></td>
									<td><a href="javascript:void(0)" class="label label-default">2</a></td>
									<td class="text-center">
									<div class="btn-group btn-group-xs">
									<a href="<?php print($this->url->get('grupos/configurar')) ?>" data-toggle="tooltip" title="" class="btn btn-block btn-imannova" data-original-title="Configurar Grupo"><i class="gi gi-cogwheel"></i> Configurar grupo</a>
									</div>
									</td>
								</tr>
								<tr>
									<td><a href="<?php print($this->url->get('grupos/configurar')) ?>">Grupo de Desarrollo</a></td>
									<td><a href="javascript:void(0)" class="label label-default">25</a></td>
									<td><a href="javascript:void(0)" class="label label-default">34</a></td>
									<td class="text-center">
									<div class="btn-group btn-group-xs">
									<a href="<?php print($this->url->get('grupos/configurar')) ?>" data-toggle="tooltip" title="" class="btn btn-block btn-imannova" data-original-title="Configurar Grupo"><i class="gi gi-cogwheel"></i> Configurar grupo</a>
									</div>
									</td>
								</tr>
								<tr>
									<td><a href="<?php print($this->url->get('grupos/configurar')) ?>">Grupo de Planificacion</a></td>
									<td><a href="javascript:void(0)" class="label label-default">4</a></td>
									<td><a href="javascript:void(0)" class="label label-default">7</a></td>
									<td class="text-center">
									<div class="btn-group btn-group-xs">
									<a href="<?php print($this->url->get('grupos/configurar')) ?>" data-toggle="tooltip" title="" class="btn btn-block btn-imannova" data-original-title="Configurar Grupo"><i class="gi gi-cogwheel"></i> Configurar grupo</a>
									</div>
									</td>
								</tr>
								<tr>
									<td><a href="<?php print($this->url->get('grupos/configurar')) ?>">Grupo de RRHH</a></td>
									<td><a href="javascript:void(0)" class="label label-default">4</a></td>
									<td><a href="javascript:void(0)" class="label label-default">11</a></td>
									<td class="text-center">
									<div class="btn-group btn-group-xs">
									<a href="<?php print($this->url->get('grupos/configurar')) ?>" data-toggle="tooltip" title="" class="btn btn-block btn-imannova" data-original-title="Configurar Grupo"><i class="gi gi-cogwheel"></i> Configurar grupo</a>
									</div>
									</td>
								</tr>
							
							</tbody>
							</table>
						</div>
					</div>
		        </center>
		    </div>
		</div>
	</div>
</div>


        <!-- Large Modal -->
        <div id="modal-nuevo-grupo" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                	<div  class="modal-header modal-formularios">
                		<h2> Creador de Grupo </h2>
                	</div>

					<div id="modalBodyCreate" class="modal-body" style="overflow: hidden; width: auto;">
						<div class="row">
							<div class="col-md-6 left-col-new form-modal">
								  <div class="form-group">
										<div class="col-md-11 center-block">
											<input type="text" class="form-control" placeholder="Nombre del grupo..."/>
										</div>
								</div>

								<div class="form-group">
									<div class="col-md-11 center-block">
									<textarea id="example-textarea-input" name="example-textarea-input" rows="9" class="form-control" placeholder="Descripción..."></textarea>
									</div>
								</div>

								<div class="form-group form-actions">
									<div class="col-md-4 ">
										<button type="submit" class="btn btn-block btn-imannova-def" data-dismiss="modal"><i class="fa fa-ban"></i> cancelar</button>
									</div>
									<div class="col-md-8 ">
										<button type="reset" class="btn btn-block btn-imannova"><i class="fa fa-check"></i> Guardar</button>
									</div>
								</div>

							 </div>

							<div class="col-md-6 right-col-new">
								<h4> <strong>Elegir o agregar</strong> personas  <a class="btn btn-md btn-imannova-action pull-right"><i class="fa fa-plus"></i> Agregar nueva persona</a></h4>

								<br><br>

								<h5>¿Quién estará en este grupo?</h5>

								<ul class="chat-users clearfix">

								<?php for ($i = 1; $i <= 11; $i++) { ?>
										<li>
										<a href="javascript:void(0)" class="chat-user-online" data-value="<?php echo $i; ?>">
										<span style="color:#1ec1b8;"><i id="check-users<?php echo $i; ?>" class="hidden hi hi-ok"></i></span>
										<img src="<?php print($this->url->get("img/avatars/avatar".$i.".jpg"))?>" alt="avatar" class="img-circle">
										</a>
										</li>
								<?php } ?>
								</ul>
							</div>							
						</div>								
					</div>
                      
               	 </div>
            </div>
        </div>

        <!-- END Large Modal -->