
<!-- modal encuesta -->

	<div class="modal-dialog modal-lg">
		<div class="modal-content">
            <!-- Updates Title -->
            <div class="block-title" style=" margin: 0px;">
                <button type="button" class="close closeModal" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2><strong>Encuesta</strong></h2>
            </div>
            <!-- END Updates Title -->
            <div class="modal-body">

				<div class="progress progress-striped active">
					<div id="barra-progreso" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 10%;"></div>
				</div>	
            	<!-- Pregunta 1 -->
				<?php $enunciado = array_shift($enunciados); ?>
			
				<div class="stp-trat"  id="stp-trat-pregunta0">
			
					<h3 class="text-center" style="padding-bottom:50px;">
						<?php print($enunciado->encd_texto) ?>
					</h3>
					<div class="form-group2 row text-center">
						<div class="col-lg-12">
							<a href="#" class="widget widget widget-hover-effect4 btn-info stp-trat-btn h" data-next="pregunta1" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<i class="gi gi-ok_2"></i>
								</div>
							</a>
						</div>	
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta1" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
								</div>
							</a>
						</div>	
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta1" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
								</div>
							</a>
						</div>
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta1" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
								</div>
							</a>
						</div>	
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta1" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
								</div>
							</a>
						</div>														
                    </div>
					<div class="form-group2 row text-center" style="margin-top: 25px; width: 83%; margin-left: auto; margin-right: auto; text-align: center;">	
						<div class="btn-group" style="width: 100%; margin-left: 4px; ">
							<?php foreach ($habilidades as $habilidad): ?>
								<a href="#" class="btn btn-primary <?php print($enunciado->hbld_id == $habilidad->hbld_id?'active':'') ?>" style="width: <?php print(((99/count($habilidades))-1).'%') ?>;border-radius: 0px; margin-left: 3px;"><?php print($habilidad->hbld_nombre) ?></a>
							<?php endforeach ?>
						</div>
                    </div>                    
				</div>

				<?php foreach ($enunciados as $key => $enunciado): ?>
					<?php $numPreg = $key+1; ?>
					<div class="stp-trat"  id="stp-trat-pregunta<?php print($numPreg) ?>" style="display:none;">
						<?php $numPreg = $key+2; ?>
						
							
						
						<h3 class="text-center" style="padding-bottom:50px;">
							<?php print($enunciado->encd_texto) ?>
						</h3>
						<?php if ($numPreg-1 == count($enunciados)): ?>
							<div class="form-group2 row text-center">
								<div class="col-lg-12">
									<a href="#" class="widget widget widget-hover-effect4 btn-info stp-trat-btn h" data-next="resultado" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>	
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>	
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>	
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>														
		                    </div>
	                	<?php else: ?>
							<div class="form-group2 row text-center">
								<div class="col-lg-12">
									<a href="#" class="widget widget widget-hover-effect4 btn-info stp-trat-btn h" data-next="<?php print('pregunta'.$numPreg) ?>" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>	
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="<?php print('pregunta'.$numPreg) ?>" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>	
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="<?php print('pregunta'.$numPreg) ?>" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="<?php print('pregunta'.$numPreg) ?>" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>	
								<div class="col-lg-12">
									<a href="#" class="widget btn-info stp-trat-btn" data-next="<?php print('pregunta'.$numPreg) ?>" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
										<div class="widget-simple">
											<i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i><i class="gi gi-ok_2"></i>
										</div>
									</a>
								</div>														
		                    </div>	                		
	                    <?php endif ?>
						<div class="form-group2 row text-center" style="margin-top: 25px; width: 83%; margin-left: auto; margin-right: auto; text-align: center;">	
							<div class="btn-group" style="width: 100%; margin-left: 4px;">
								<?php foreach ($habilidades as $habilidad): ?>
									<a href="#" class="btn btn-primary <?php print($enunciado->hbld_id == $habilidad->hbld_id?'active':'') ?>" style="width: <?php print(((99/count($habilidades))-1).'%') ?>;border-radius: 0px; margin-left: 3px;"><?php print($habilidad->hbld_nombre) ?></a>
								<?php endforeach ?>
							</div>
	                    </div>                    
					</div>
				<?php endforeach ?>


				<!-- Resultado -->		

				<div class="stp-trat"  id="stp-trat-resultado" style="display:none;">
					<div class="form-group row text-center" style="margin-top: -15px;">
						<div class="col-lg-12"  style="margin-top:20%">
							<h2><i class="fa fa-hand-peace-o fa-3x"></i><br>¡<strong>Gracias</strong> por responder!</h2> <br>
						</div>
					</div>
				</div>																							
            </div>

            <input type="hidden" id="contador" value=0>



		
            <div class="modal-footer">
                <div class="btn-group btn-group-sm pull-right">
                    <a id="cerrarModal" class="btn btn-sm btn-default pull-right" data-dismiss="modal" href="" > Cerrar</a>
                </div>
            </div>
		</div>
	</div>


	<script>
            $('.stp-trat-btn').click(
                function(){
                    $('#stp-trat-'+$(this).data('stp')+' .stp-trat-btn').removeClass('active');
                    $(this).addClass('active');

                    $('.stp-trat').css('display','none');
                    
                    $('#stp-trat-'+$(this).data('next')).css('display','block');


                    <?php print(isset($jsScript)?$jsScript:'') ?>

                    if(100 * parseFloat($('#barra-progreso').css('width')) / parseFloat($('#barra-progreso').parent().css('width')) > 33){
                        $('#barra-progreso').removeClass('progress-bar-danger');
                        $('#barra-progreso').addClass('progress-bar-warning');
                    }

                    if(100 * parseFloat($('#barra-progreso').css('width')) / parseFloat($('#barra-progreso').parent().css('width')) > 66){
                        $('#barra-progreso').removeClass('progress-bar-warning');
                        $('#barra-progreso').addClass('progress-bar-success');
                    }                    
                }
            );		


	</script>
