<div class="container">


		<div class="left-col-new" style="text-align: center; min-height: 100px;">

			<div class="row center-block">
			<div class="col-lg-4">
				<div class="profile-header-container">   
		    		<div class="profile-header-img">
		                <img class="img-circle" src="<?php print($this->url->get("img/avatars/avatar4.jpg"))?>" />
		                <!-- badge -->
		                <div class="rank-label-container">
		                    <span class="label label-default rank-label">Equipo de Soporte</span>
		                </div>
		            </div>
		        </div> 
	        </div>
	        <div class="col-lg-4">
	        <h2> Responder Evaluación</h2>
	        <h3> Evaluando a: <strong> Felipe Jorquera A. </strong> </h3>
	        </div>
			</div>
		</div>

		<div class="col-lg-10 col-md-10 col-sm-12 center-block bhoechie-tab">
		    <!-- flight section -->
		    <div class="bhoechie-tab-content fade in active">
		    	<div class="row">
				<h2>Selecciona 3 habilidades a evaluar </h2>
			    <div class="form-group">
			        <div class="col-sm-12 col-md-12 col-lg-12">
			            <input type="search" class="form-control" id="search" placeholder="Buscar Habilidad...">
			        </div>
			    </div>
			    </div>
			    <div class="row">
			        <div class="form-group">
			            <div class="searchable-container">

			            	<?php foreach ($pcData['encuesta'] as $habilidad) { ?>
			            		
			            	
			                <div class="items col-xs-12 col-sm-5 col-md-3 col-lg-3">
			                    <div class="info-block block-info clearfix">
			                        <div class="square-box pull-left">
			                            <span class="glyphicon glyphicon-tags glyphicon-lg"></span>
			                        </div>
			                        <div data-toggle="buttons" class="btn-group bizmoduleselect">
			                            <label class="btn btn-default">
			                                <div class="bizcontent">
			                                    <input type="checkbox" name="var_id[]" autocomplete="off" value="<?php print($habilidad['id']) ?>">
			                                    <span class="glyphicon glyphicon-ok glyphicon-lg"></span>
			                                    <h5><?php print_r($habilidad['nombre']);?></h5>
			                                </div>
			                            </label>
			                        </div>
			                    </div>
			                </div>
			               <?php } ?>
			            </div>
			        </div>
				</div>
		    </div>

		    <div class="" style="text-align: center; padding-top: 50px;">
		    	<div class="block-title clearfix" style="width: 50%; display: inline-block;">
					<a  id="btnResponder"
						data-val="id=1,2,3"
    					data-action="<?php echo $this->url->get("ajax/cargarEncuesta") ?>"
					    href="<?php echo $this->url->get("ajax/cargarEncuesta") ?>"
						data-eval="$('#modal-large').modal('show');" 
						class="menu-config-grupo list-group-item bg-primary text-center btn-modal"
						disabled>
					<i class="fa fa-plus fa-3x "></i><br/>Responder Evaluación
					</a>
				</div>
			</div>

		</div>



</div>

<div id="modal-encuesta" data-keyboard="false" data-backdrop="static" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
</div>

