<div id="contenidomodal">
    
</div>


<!-- Widgets Row -->
<div class="row">
<div class="container">
    <div class="row user-menu-container square">
        <div class="col-md-7 user-details">
            <div class="row coralbg white">
                <div class="col-md-6 no-pad">
                    <div class="user-pad">
                        <h3> <?php print($pcData['user']->name) ?></h3>
                        <h5 class="white"><i class="gi gi-group"></i> <?php print($pcData['grupo']?$pcData['grupo']->grpo_nombre:'Aún no perteneces a ningún grupo') ?></h5>
                        <h4 class="white"><i class="gi gi-envelope"></i> <?php print($pcData['user']->email) ?></h4>

                    </div>
                </div>
                <div class="col-md-6 no-pad">
                    <div class="user-image">
                    			  
                        <img src="<?php print($this->url->get("img/profile-img.jpg"))?>" class="img-responsive thumbnail">
                    </div>
                </div>
            </div>
            <div class="row overview">
                <div class="col-md-4 user-pad text-center">
                    <h3>PUNTOS</h3>
                    <h4><?php print($pcData['user']->puntos) ?></h4>
                </div>
                <div class="col-md-4 user-pad text-center" style="padding-left: 0">
                    <h3>RECONOCIMIENTOS</h3>
                    <h4><?php print_r($pcData['totalreconocimientos']); ?></h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>HABILIDADES RECONOCIDAS</h3>
                    <h4><?php print_r($pcData['totalhabilidadesreconocidas']."/20"); ?></h4>
                </div>
            </div>
        </div>
        <div class="col-md-1 user-menu-btns">
            <div class="btn-group-vertical square" id="responsive">
                <a href="#" class="btn btn-block active">
                 <i class="gi gi-star fa-3x"></i>
                </a>
                <a href="#" class="btn t">
                  <i class="gi gi-log_book fa-3x"></i>
                </a>
                <a href="#" class="btn ">
                  <i class="fa fa-group fa-3x"></i>
                </a>
                <a href="#" class="btn ">
                  <i class="hi hi-bell fa-3x"></i>
                </a>
            </div>
        </div>
        <div class="col-md-4 user-menu user-pad">
            <div class="user-menu-content active">
                <h3>
                   Mis Habilidades Destacadas
                </h3>
                <ul class="user-menu-list">
                    <li>
                        <img src="img/medal1.png" width="45" title="Liderazgo"><h5>Lider Innato</h5>
                    </li>
                    <li>
                        <img src="img/medal2.png" width="45" title="Trabajo en Equipo"><h5>El Mejor Compañero</h5>
                    </li>
                    <li>
                        <img src="img/medal3.png" width="45" title="Responsabilidad"><h5>Señor Responsable</h5>
                    </li>
                </ul>
            </div>
                
            <div class="user-menu-content">
                <h3>
                    Mis Encuestas Respondidas
                </h3>
                <ul class="user-menu-list">
                <?php

                    foreach ($pcData['fecha'] as $val) {
                    $meses = array('','Enero ','Febrero ','Marzo ', 'Abril ', 'Mayo ', 'Junio ', 'Julio ', 'Agosto ', 'Septiembre ', 'Octubre ', 'Noviembre ', 'Diciembre ');
                       
                 ?>
                    <li>
                        <h4><?php print_r($meses[$val->mes]); ?> <small class="coral"> <i class="gi gi-edit"></i> <?php print_r($val->cantidad); ?></small></h4>
                    </li>
                <?php }; ?>
                </ul>
            </div>
            
            <div class="user-menu-content">
                <h3>
                    Mis equipos de trabajo
                </h3>
                <div class="row">
                <?php 
                for ($i=0; $i < count($pcData['grupos']); $i++) { ?>   
                 
                    <div class="col-md-6" style="margin-bottom: 10px">
                        
                        <div class="info">
                            <p class="small" style="text-overflow: ellipsis"><strong> <?php print_r($pcData['grupos'][$i]['NombreGrupo']); ?></strong></p>
                            <p class="small coral text-right"><i class="fa fa-group"> </i><?php print_r($pcData['usuarios'][$i]['Usuarios']); ?> Personas</small>
                        </div>
                        <div class="stats turqbg">
                            <span> <strong><?php print_r($pcData['reconocimiento'][$i]['Reconocimientos']); ?> Reconocimientos recibidos</strong></span>
                        </div>
                    </div>
                <?php } ?>
                    
                </div>
            </div>
            <div class="user-menu-content">
                <h2 class="text-center">
                    HISTORIAL
                </h2>
                <div class="share-links">
            		<div class="fix-historial">
                    <?php 
                        foreach ($pcData['historial'] as $hito) { ?>
                    	<h5><b><?php print_r("{$hito->fecha}"); ?> - </b><?php print_r($hito->hito); ?></h5>
                    <?php } ?>
                	</div>
            	</div>
        	</div>
        </div>
    </div>


    <div class="row" style="padding-top: 40px;">
    	<div class="col-lg-6">
    		<div class="widget">
				<div class="widget-extra themed-background-dark-night text-center">
					<h3 class="widget-content-light">Habilidades <strong>Blandas</strong></h3>
				</div>
				 <div id="chart_div"></div>
			</div>
		</div>

    	<div class="col-lg-6">
    		<div class="widget">
				<div class="widget-extra themed-background-dark-night text-center">
					<h3 class="widget-content-light">Historia <strong> Puntos Acumulados</strong></h3>
				</div>
				 <div id="chart_div2"></div>
			</div>
		</div>

    </div>



</div>
</div>



<!-- END Widgets Row -->