<!-- Widgets Row -->
<div class="row">
<div class="container">
    <div class="row user-menu-container square">
        <div class="col-md-7 user-details">
            <div class="row coralbg white">
                <div class="col-md-6 no-pad">
                    <div class="user-pad">
                        <h3>Mackarena Astudillo</h3>
                        <h4 class="white"><i class="gi gi-group"></i> Equipo de Soporte</h4>
                        <h4 class="white"><i class="gi gi-envelope"></i> mastudillo@imannova.cl</h4>

                    </div>
                </div>
                <div class="col-md-6 no-pad">
                    <div class="user-image">
                    			  
                        <img src="<?php print($this->url->get("img/profile-img.jpg"))?>" class="img-responsive thumbnail">
                    </div>
                </div>
            </div>
            <div class="row overview">
                <div class="col-md-4 user-pad text-center">
                    <h3>COMPENSACIÓN</h3>
                    <h4>478 Pts</h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>EVALUACIONES</h3>
                    <h4>21</h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>HABILIDADES</h3>
                    <h4>6</h4>
                </div>
            </div>
        </div>
        <div class="col-md-1 user-menu-btns">
            <div class="btn-group-vertical square" id="responsive">
                <a href="#" class="btn btn-block btn-default active">
                 <i class="gi gi-star fa-3x"></i>
                </a>
                <a href="#" class="btn t">
                  <i class="gi gi-log_book fa-3x"></i>
                </a>
                <a href="#" class="btn ">
                  <i class="fa fa-group fa-3x"></i>
                </a>
                <a href="#" class="btn ">
                  <i class="hi hi-bell fa-3x"></i>
                </a>
            </div>
        </div>
        <div class="col-md-4 user-menu user-pad">
            <div class="user-menu-content active">
                <h3>
                   Mis Habilidades Destacadas
                </h3>
                <ul class="user-menu-list">
                    <li>
                        <h4><i class="gi gi-certificate coral"></i></i> Liderazgo.</h4>
                    </li>
                    <li>
                        <h4><i class="gi gi-certificate coral"></i></i> Trabajo en equipo.</h4>
                    </li>
                    <li>
                        <h4><i class="gi gi-certificate coral"></i></i> Expresión oral</h4>
                    </li>
                </ul>
            </div>
            <div class="user-menu-content">
                <h3>
                    Mis Encuestas Respondidas
                </h3>
                <ul class="user-menu-list">
                    <li>
                        <h4>Marzo <small class="coral"> <i class="gi gi-edit"></i> 4</small></h4>
                    </li>
                    <li>
                        <h4>Febrero <small class="coral"><i class="gi gi-edit"></i> 10 </small></h4>
                    </li>
                    <li>
                        <h4>Enero <small class="coral"><i class="gi gi-edit"></i> 1</small></h4>
                    </li>
                </ul>
            </div>
            <div class="user-menu-content">
                <h3>
                    Mis equipos de trabajo
                </h3>
                <div class="row">
                    <div class="col-md-6">
                        <div class="view">
                            <div class="caption">
                                <a href="" rel="tooltip" title="Appreciate"><span class="fa fa-heart-o fa-2x"></span></a>
                                <a href="" rel="tooltip" title="View"><span class="fa fa-search fa-2x"></span></a>
                            </div>
                            <img src="" class="img-responsive">
                        </div>
                        <div class="info">
                            <p class="small" style="text-overflow: ellipsis"><strong>Soporte</strong></p>
                            <p class="small coral text-right"><i class="fa fa-group"></i> 35 Personas</small>
                        </div>
                        <div class="stats turqbg">
                            <span> <strong>15 Evaluaciones recibidas</strong></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="view">
                            <div class="caption">
                                <a href="" rel="tooltip" title="Appreciate"><span class="fa fa-heart-o fa-2x"></span></a>
                                <a href="" rel="tooltip" title="View"><span class="fa fa-search fa-2x"></span></a>
                            </div>
                            <img src="" class="img-responsive">
                        </div>
                        <div class="info">
                            <p class="small" style="text-overflow: ellipsis"><strong>Gerencia Proyectos</strong></p>
                            <p class="small coral text-right"><i class="fa fa-group"></i> 7 Personas</small>
                        </div>
                        <div class="stats turqbg">
                            <span> <strong> 6 Evaluaciones recibidas</strong></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="user-menu-content">
                <h2 class="text-center">
                    HISTORIAL
                </h2>
                <div class="share-links">
            		<div class="fix-historial">
                    	<h5> <b> 07/03/2016 - </b>Haz aumentado 50 Pts el último mes</h5>
                    	<h5> <b> 05/02/2016 - </b>Haz logrado mejorar Liderazgo </h5>
                    	<h5> <b> 04/01/2016 - </b>Destacado en Expresion Oral en 2015</h5>

                	</div>
            	</div>
        	</div>
        </div>
    </div>


    <div class="row" style="padding-top: 40px;">
    	<div class="col-lg-6">
    		<div class="widget">
				<div class="widget-extra themed-background-dark-night text-center">
					<h3 class="widget-content-light">Habilidades <strong>Blandas</strong></h3>
				</div>
				 <div id="chart_div"></div>
			</div>
		</div>

    	<div class="col-lg-6">
    		<div class="widget">
				<div class="widget-extra themed-background-dark-night text-center">
					<h3 class="widget-content-light">Historia <strong> Puntos Compensación</strong></h3>
				</div>
				 <div id="chart_div2"></div>
			</div>
		</div>

    </div>



</div>
</div>



<!-- END Widgets Row -->