<div class="content-header">
    <div class="header-section">  
<h1>
	<img class="pull-right" style="width:9%; margin-top:-27px;height:100px;width:150px"src="<?php echo $this->url->get("/img/bc-chile.png"); ?>" alt="">
		Consultar <strong>Solicitud</strong><br> 
		<small>Sistema de Solicitudes</small>
</h1>     
    </div>
</div>
				

			
			<div class="row fwBody draggable-blocks">
				<div class="col-sm-4 connectedSortable" data-col="0">
					<!-- Icon Search Block -->
					<div class="block full" data-col="0" data-row="0" data-idob="1">
						<!-- Icon Search Title -->
						<div class="block-title">
							<h2>Información<strong>Personal</strong></h2>
						</div>

						<a href="javascript:void(0)" class="widget widget-hover-effect2 themed-background-flatie">
							<div class="widget-simple">
								<h4 class="widget-content widget-content-light">
									<strong>Miguel Jara Orozco</strong>
									<small>miguel.jara@zentagroup.com, +56.9.84193351</small>
									<small>Ciudad:Chimbarongo</small>
								</h4>
							</div>
						</a>
						
					</div>
					<!-- END Icon Search Block -->
				</div>
				<div class="col-sm-4 connectedSortable" data-col="1">
					<!-- Icon Search Block -->
					<div class="block full" data-col="1" data-row="0" data-idob="2">
						<!-- Icon Search Title -->
						<div class="block-title">
							<h2><strong>RRHH</strong></h2>
						</div>

						<a href="javascript:void(0)" class="widget widget-hover-effect2 themed-background-default">
							<div class="widget-simple">
								<h4 class="widget-content widget-content-light">
									<strong>Ultima Liquidación</strong> <span style="font-size: 13px;">05-01-2016</span>
									<small>Vacaciones Pendientes <b>20 días</b></small>
									<small>AFP <b>Cuprum,</b> Isapre <b>Banmedica</b></small>
								</h4>
							</div>
						</a>
						
					</div>
					<!-- END Icon Search Block -->
					<!-- Icon Search Block -->
					<div class="block full" data-col="1" data-row="1" data-idob="3">
						<!-- Icon Search Title -->
						<div class="block-title">
							<h2><strong>OTRO</strong></h2>
						</div>

						<a	href="<?php echo $this->url->get("ajax");?>"
							data-action="<?php echo $this->url->get("ajax");?>"
							data-val="" 
							class="widget widget-hover-effect2 themed-background-default">
							<div class="widget-simple">
								<h4 class="widget-content widget-content-light">
									<strong>Ultima Liquidación</strong> <span style="font-size: 13px;">05-01-2016</span>
									<small>Vacaciones Pendientes <b>20 días</b></small>
									<small>AFP <b>Cuprum,</b> Isapre <b>Banmedica</b></small>
								</h4>
							</div>
						</a>
						
					</div>
					<!-- END Icon Search Block -->			
				</div>
				<div class="col-sm-4 connectedSortable" data-col="2">
					<!-- Icon Search Block -->
					<div class="block full" data-col="2" data-row="0" data-idob="4">
						<!-- Icon Search Title -->
						<div class="block-title">
							<h2><strong>Proyectos</strong></h2>
						</div>

						<a href="javascript:void(0)" class="widget widget-hover-effect2 themed-background-waterlily">
							<div class="widget-simple">
								<h4 class="widget-content widget-content-light">
									<strong>LAN.iso BAGTAG</strong><small>inicio:05-01-2016</small>
									<strong>LAN CARGO CRONOS</strong><small>inicio:05-10-2015, fin: 04-01-2016</small>
								</h4>
							</div>
						</a>
						
					</div>
					<!-- END Icon Search Block -->
				</div>
			</div>
			<div id="contenidomodal">
			</div>